apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: dedicatedgameservers.azure.com
spec:
  group: azure.com
  version: v1
  scope: Namespaced
  names:
    kind: DedicatedGameServer
    plural: dedicatedgameservers
    singular: dedicatedgameserver
    shortNames:
    - dgs
  validation:
   # openAPIV3Schema is the schema for validating custom objects.
    openAPIV3Schema:
      properties:
        spec:
          properties:
            Image:
              type: string
              pattern: '^(?!\s*$).+' # non-empty string
            StartMap:
              type: string
              pattern: '^(?!\s*$).+'
            Port:
              type: integer
              minimum: 20000
              maximum: 30000
  