apiVersion: v1
kind: Pod
metadata:
  name: openarena
  labels:
    name: openarena
spec:
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
  containers:
  - name: openarena
    image: docker.io/dgkanatsios/docker_openarena_k8s:latest
    env:
    - name: OA_STARTMAP
      value: "dm4ish"
    - name: OA_PORT
      value: "27960"
    volumeMounts:
      - name: openarenavolume
        mountPath: /data
    ports:
    - containerPort: 27960
      protocol: UDP  
  volumes:
  - name: openarenavolume
    azureFile:
      secretName: openarena-storage-secret
      shareName: openarenadata
      readOnly: false
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: openarena
#   labels:
#     name: openarena
# spec:
#   ports:
#     # the port that this service should serve on
#     - port: 33333
#       targetPort: 27960
#       protocol: UDP 
#       name: port1
#   # label keys and values that must match in order to receive traffic for this service
#   selector:
#     name: openarena
#   type: NodePort
#   externalIPs: 
#   - 52.170.95.251
