apiVersion: v1
kind: Pod
metadata:
  name: iperf-with-service
  labels:
    name: iperf-with-service
spec:
  containers:
  - name: iperf-with-service
    image: networkstatic/iperf3
    args: ["-s","-p","25001", "-V"]
    ports:
    - containerPort: 25001
      protocol: UDP  
      name: port25001
---
apiVersion: v1
kind: Service
metadata:
  name: iperf-service
spec:
  ports:
    # the port that this service should serve on
    - port: 25001
      targetPort: port25001
      protocol: UDP 
      name: port25001
  # label keys and values that must match in order to receive traffic for this service
  selector:
    name: iperf-with-service
  type: LoadBalancer